function def = canonical_feature_definition()
%CANONICAL_FEATURE_DEFINITION Ordered 41-feature classifier schema.

codes = [ ...
    "emav"; "ewl"; "fzc"; "asm"; "ass"; "ltkeo"; "card"; ...
    "ldasdv"; "ldamv"; "dvarv"; "vo"; "tm"; "damv"; ...
    "ar1"; "ar2"; "ar3"; "ar4"; ...
    "mad"; "iqr"; "skew"; "kurt"; "cov"; "sd"; "var"; ...
    "ae"; "iemg"; "mav"; "ssc"; "zc"; "wl"; "rms"; ...
    "aac"; "dasdv"; "ld"; "mmav"; "mmav2"; "myop"; ...
    "ssi"; "vare"; "wa"; "mfl"];

names = [ ...
    "EnhancedMeanAbsoluteValue"; ...
    "EnhancedWavelength"; ...
    "NewZeroCrossing"; ...
    "AbsoluteValueOfSummationOfExpRoot"; ...
    "AbsoluteValueOfSummationOfSquareRoot"; ...
    "LogTeagerKaiserEnergyOperator"; ...
    "Cardinality"; ...
    "LogDifferenceAbsoluteStandardDeviation"; ...
    "LogDifferenceAbsoluteMeanValue"; ...
    "DifferenceVarianceValue"; ...
    "V_Order"; ...
    "TemporalMoment"; ...
    "DifferenceAbsoluteMeanValue"; ...
    "AutoregressionModelT1"; ...
    "AutoregressionModelT2"; ...
    "AutoregressionModelT3"; ...
    "AutoregressionModelT4"; ...
    "MeanAbsoluteDeviation"; ...
    "InterquartileRange"; ...
    "Skewness"; ...
    "Kurtosis"; ...
    "CoefficientOfVariation"; ...
    "StandardDeviation"; ...
    "Variance"; ...
    "AverageEnergy"; ...
    "IntegratedEMG"; ...
    "MeanAbsoluteValue"; ...
    "SlopeSignChange"; ...
    "ZeroCrossing"; ...
    "WaveformLength"; ...
    "RMS"; ...
    "AverageAmplitudeChange"; ...
    "DifferenceAbsoluteStandardDeviationValue"; ...
    "LogDetector"; ...
    "ModifiedMeanAbsoluteValue"; ...
    "ModifiedMeanAbsoluteValue2"; ...
    "MyopulsePercentageRate"; ...
    "SimpleSquareIntegral"; ...
    "VarianceOfEMG"; ...
    "WillisonAmplitude"; ...
    "MaximumFractalLength"];

assert(numel(codes) == 41 && numel(names) == 41, ...
    'Canonical feature definition must contain exactly 41 rows.');
def = table(codes, names, 'VariableNames', {'Code','Name'});
end
